if module is not loaded, we exit

diff --git a/testbed/trunk/testbed/lib/io b/testbed/trunk/testbed/lib/io
--- a/testbed/trunk/testbed/lib/io
+++ b/testbed/trunk/testbed/lib/io
@@ -277,3 +277,11 @@ io_uncompress_file()
 	esac
 	echo $uncompressed_file
 }
+
+io_exit_with_error()
+{
+	local error_string=$@
+	error "$error_string"
+	error "Exiting..."
+	exit 1
+}
