Now each line of verbose,debug,error will be head by a colored action

diff --git a/testbed/trunk/testbed/lib/io b/testbed/trunk/testbed/lib/io
--- a/testbed/trunk/testbed/lib/io
+++ b/testbed/trunk/testbed/lib/io
@@ -14,7 +14,7 @@ COLOR_YELLOW="\033[1;33m"
 COLOR_WHITE="\033[1;37m"
 COLOR_NO_COLOR="\033[0m"
 
-VERBOSE_COLOR=$COLOR_LIGHT_PURPLE
+VERBOSE_COLOR=$COLOR_YELLOW
 DEBUG_COLOR=$COLOR_LIGHT_GREEN
 ERROR_COLOR=$COLOR_LIGHT_RED
 
@@ -24,9 +24,8 @@ verbose()
 	local str=$1
 	local options=$2
 	if [[ -n $VERBOSE ]]; then
-		echo -en $VERBOSE_COLOR
+		echo -en "${VERBOSE_COLOR}verbose: $COLOR_NO_COLOR" >&2
 		echo $options "$str" >&2
-		echo -en $COLOR_NO_COLOR
 	fi
 }
 
@@ -35,9 +34,8 @@ debug()
 	local str=$1
 	local options=$2
 	if [[ -n $DEBUG ]]; then
-		echo -en $DEBUG_COLOR
-		echo $options "DEBUG: $str" >&2
-		echo -en $COLOR_NO_COLOR
+		echo -en "${DEBUG_COLOR}debug: $COLOR_NO_COLOR" >&2
+		echo $options "$str" >&2
 	fi
 }
 
@@ -57,9 +55,8 @@ error()
 {
 	local str=$1
 	local options=$2
-	echo -en $ERROR_COLOR
-	echo $options "Error: $str" >&2
-	echo -en $COLOR_NO_COLOR
+	echo -en "${ERROR_COLOR}error: $COLOR_NO_COLOR" >&2
+	echo $options "$str" >&2
 }
 
 create_temp_file()
